[pytest]
# Minimum version of pytest required
minversion = 7.0

# Test paths (directory or file pattern)
testpaths = tests

# Additional options by default
addopts = -v

# Python path (root folder)
pythonpath = .